mt/mt/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('places.urls')),
]

mt/places/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView

from . import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='spending/index.html')),
    url(r'^add_category/$', views.CategoryListView.as_view(), name="add-category"),
    url(r'^add_note/$', views.NoteListView.as_view(), name="add-note"),
    url(r'^add_place/$', views.PlaceListView.as_view(), name="add-place"),

    url(r'^list_category/$', views.CategoryListView.as_view(), name="list-category"),
    url(r'^list_note/$', views.NoteListView.as_view(), name="list-note"),
    url(r'^list_place/$', views.PlaceListView.as_view(), name="list-place"),
]

mt/budget/models.py
import decimal

from django.db import models
from django.contrib.auth.models import User


class BudgetLog(models.Model):
    """
    Money allocation towards an item
    """
    timestamp = models.DateTimeField()
    amount = models.DecimalField(max_digits=11, decimal_places=2)
    category = models.ForeignKey('places.Category', blank=True, null=True)

    def __str__(self):
        amount = "%s" % (self.amount)
        if self.category:
            result = '%s: %s' % (amount, self.category.name)
        return result


class BudgetItem(models.Model):
    """
    An item user is saving money for
    """
    ANNUAL = 'annually'
    BIMONTHLY = 'bimonthly'
    MONTHLY = 'monthly'
    DAILY = 'daily'
    RATE_CHOICES = (
        (ANNUAL, 'Anually'),
        (BIMONTHLY, 'Bi-Monthly'),
        (MONTHLY, 'Monthly'),
        (DAILY, 'Daily')
    )

    created = models.DateTimeField()
    updated = models.DateTimeField()
    name = models.CharField(max_length=255)
    rate = models.CharField(max_length=65, choices=RATE_CHOICES)
    amount = models.DecimalField(max_digits=11, decimal_places=2)
    logs = models.ManyToManyField(BudgetLog)
    user = models.ForeignKey(User)

    def __str__(self):
        return "%s %s\% %s" % (self.name, (self.amount/self.total())*100, self.get_rate_name())

    def total(self):
        try:
            return sum(self.logs.values_list('amount', flat=True))
        except KeyError:
            return decimal.Decimal('0.0')

    def get_rate_name(self):
        return dict(self.RATE_CHOICES).get(self.rate, '')

mt/places/models.py
# from django.contrib.gis.db import models
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(blank=True, default=u'', max_length=255)

    def __str__(self):
        return "%s" % self.name


class Note(models.Model):
    """
    Note about something, like a place you ate at
    """
    timestamp = models.DateTimeField('date taken', blank=True, null=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, default=u'')
    user = models.ForeignKey(User)

    # objects = models.GeoManager()

    def save(self, *args, **kwargs):
        if not self.id:
            self.timestamp = timezone.now()
        super(Note, self).save(*args, **kwargs)

    def __str__(self):
        return "%s" % self.name


class Place(models.Model):
    """
    decimal  decimal     distance
    places   degrees    (in meters)
    -------  ---------  -----------
      1      0.1000000  11,057.43      11 km
      2      0.0100000   1,105.74       1 km
      3      0.0010000     110.57
      4      0.0001000      11.06
      5      0.0000100       1.11
      6      0.0000010       0.11      11 cm
      7      0.0000001       0.01       1 cm

    -- https://stackoverflow.com/a/16743805

    Latitude in degrees is -90 and +90
    Longitude is in the range -180 and +180

    1+2+1+7 == 11
    1+3+1+7 == 12
    """
    name = models.CharField(max_length=255)
    # Geos Libraries are a nightmare to install
    # removing them until better OS package support is available
    # location = models.PointField(blank=True, null=True)
    lng = models.DecimalField(max_digits=12, decimal_places=7, blank=True, null=True)
    lat = models.DecimalField(max_digits=12, decimal_places=7, blank=True, null=True)
    notes = models.ManyToManyField(Note, blank=True)
    categories = models.ManyToManyField(Category, blank=True)

    def __str__(self):
        return "%s" % self.name

mt/transactions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from slugify import slugify

from places.models import Place

CASH = 'cash'
SAVINGS = 'savings'
CHECKING = 'checking'
CREDIT = 'credit'
PAYPAL = 'paypal'
VENMO = 'venmo'
BITCOIN = 'bitcoin'
DESTINATION = 'destination'
REV_TYPE = [
    (CASH, 'Cash'),
    (SAVINGS, 'Savings Account'),
    (CHECKING, 'Checking Account'),
    (CREDIT, 'Credit Card'),
    (PAYPAL, 'PayPal Account'),
    (VENMO, 'Venmo Account'),
    (BITCOIN, 'Bitcoin Account'),
]


class Account(models.Model):
    """A User's Account"""
    name = models.CharField(max_length=255)
    account_type = models.CharField(max_length=255, choices=REV_TYPE, blank=True, default=u'')
    person = models.ForeignKey(User, blank=True, null=True)
    balance = models.DecimalField(max_digits=11, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return '%s %s' % (self.name, self.account_type.capitalize())


PERSON = 'person'
ACCOUNT = 'account'
PLACE = 'place'
SOURCE_TYPE = [
    (PERSON,  'person'),
    (ACCOUNT, 'account'),
    (PLACE, 'place')
]


class Entity(models.Model):
    """The source or destination of a transaction

    Can either be a person or a place (such as a resturant)
    """
    name = models.CharField(max_length=255)
    source_type = models.CharField(choices=SOURCE_TYPE, max_length=255)

    person = models.ForeignKey(User, blank=True, null=True)
    place = models.ForeignKey(Place, blank=True, null=True)
    account = models.ForeignKey(Account, blank=True, null=True)

    def __str__(self):
        if self.person and self.person.first_name:
            return self.person.first_name
        elif self.account and self.account.name:
            return self.account.name
        elif self.place and self.palce.name:
            return self.place.name
        return self.name


def handle_receipt_upload(instance, filename):
    # import pdb; pdb.set_trace()
    _place = 'uncategorized'
    _date = timezone.now().strftime('%Y-%m-%d')
    # _date = instance.timestamp.strftime('%Y-%m-%d')
    if instance.place and instance.place.name:
        _place = slugify(instance.place.name)
    return 'receipt/%(date)s--%(place)s/%(fname)s' % {
        'date': _date,
        'place': _place,
        'fname': filename
    }


class Receipt(models.Model):
    description = models.TextField(blank=True, default=u'')
    receipt = models.ImageField(blank=True, null=True, upload_to=handle_receipt_upload)
    receipt_text = models.TextField(blank=True, default=u'')  # TODO: populate via OCR
    place = models.ForeignKey(Place, blank=True, null=True)

    def __str__(self):
        return "%s" % self.description


PURCHASE = 'pur'
LOAN = 'loan'
PAYMENT = 'payment'
TRANSACTION_TYPES = [
    (PAYMENT, 'Payment'),
    (PURCHASE, 'Purchase'),
    (LOAN, 'Loan'),
]


class Transaction(models.Model):
    source = models.ForeignKey(Entity, related_name='sources')
    dest = models.ForeignKey(Entity, related_name='dests')
    amount = models.DecimalField(max_digits=11, decimal_places=2)
    transaction_type = models.CharField(max_length=60, choices=TRANSACTION_TYPES, default=PURCHASE)

    note = models.TextField(blank=True, null=True)
    receipt = models.ForeignKey(Receipt, blank=True, null=True)

    # Only one transaction from source to destination can happen
    # in a given datetime
    guid = models.CharField(max_length=255, blank=True, default=u'')
    timestamp = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.guid:
            self.guid = '%s|%s' % (self.source_id, self.dest_id)
        super(Transaction, self).save(*args, **kwargs)

    def __str__(self):
        return '$%(amount)s from %(source_name)s to %(dest_name)s' % {
            'amount': self.amount,
            'source_name': self.source.name,
            'dest_name': self.dest.name,
        }

    class Meta:
        ordering = ('timestamp',)
        unique_together = ('guid', 'timestamp')

mt/places/forms.py
from django.forms import ModelForm

from . import models

mt/places/views.py
from rest_framework import generics
from rest_framework import renderers

from . import models, serializers


class CategoryListView(generics.ListCreateAPIView):
    queryset = models.Category.objects.all()
    serializer_class = serializers.CategorySerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def list(request, *args, **kwargs):
        pass

    def create(request, *args, **kwargs):
        pass


class CategoryDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Category.objects.all()
    serializer_class = serializers.CategorySerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def retrieve(request, *args, **kwargs):
        pass

    def update(request, *args, **kwargs):
        pass

    def partial_update(request, *args, **kwargs):
        pass

    def destroy(request, *args, **kwargs):
        pass


class NoteListView(generics.ListCreateAPIView):
    queryset = models.Note.objects.all()
    serializer_class = serializers.NoteSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def list(request, *args, **kwargs):
        pass

    def create(request, *args, **kwargs):
        pass


class NoteDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Note.objects.all()
    serializer_class = serializers.NoteSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def retrieve(request, *args, **kwargs):
        pass

    def update(request, *args, **kwargs):
        pass

    def partial_update(request, *args, **kwargs):
        pass

    def destroy(request, *args, **kwargs):
        pass


class PlaceListView(generics.CreateAPIView):
    queryset = models.Place.objects.all()
    serializer_class = serializers.PlaceSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def list(request, *args, **kwargs):
        pass

    def create(request, *args, **kwargs):
        pass


class PlaceDetailView(generics.ListCreateAPIView):
    queryset = models.Place.objects.all()
    serializer_class = serializers.PlaceSerializer
    renderer_classes = (renderers.TemplateHTMLRenderer,renderers.JSONRenderer)

    def retrieve(request, *args, **kwargs):
        pass

    def update(request, *args, **kwargs):
        pass

    def partial_update(request, *args, **kwargs):
        pass

    def destroy(request, *args, **kwargs):
        pass

mt/places/templates/spending/backbone.html
<script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.2.3/backbone-min.js"></script>
<script>
if(typeof(Backbone) === 'undefined') {
    document.write('<script src="lib/backbone/backbone.js"><\/script>');
}
</script>

mt/places/templates/spending/index.html
{% extends 'mt/base.html' %}
{% load static %}
{% block head %}
{% comment %}
<style>
#map {
    height: 400px;
    width: 100%;
}
</style>
{% endcomment %}
{% endblock %}

{% block main %}
<h1>Coming Soon</h1>
{% comment %}
<div id="log-spending-page"></div>
<div id="log-place-page"></div>
<div id="log-note-page"></div>
<div id="log-category-page"></div>

<ul class="add-links">
    <li>
        <a href="#log-place-page">Add Place</a>
    </li>
</ul>
{% endcomment %}
{% endblock %}

{% block js %}
{{ block.super }}

{% comment %}
<script type="text/html" id="tmpl-add-spending-form">
    <form id="add-spending">
        <input id="id_timestamp" name="timestamp" type="datetime-local">
        <input id="id_amount" name="amount" type="number" placeholder="1.0" step="0.01" min="0">
        <textarea id="id_description" name="description"></textarea>
        <input id="id_receipt" name="receipt" type="file">
        <textarea id="id_receipt_text" name="receipt_text"></textarea>
        <input id="id_place" name="place" type="hidden">
    </form>
</script>

<script type="text/html" id="tmpl-add-place-form">
    <form id="add-place">
        <input id="id_name" name="name" type="text">
        <div id="map"></div>
        <input id="id_lat" name="lat" type="hidden" value="">
        <input id="id_lng" name="lng" type="hidden" value="">
        <input id="id_notes" name="notes" type="hidden">
        <input id="id_categories" name="categories" type="hidden">
    </form>
</script>

<script type="text/html" id="tmpl-note-form">
    <form id="add-note">
        <input id="id_timestamp" name="timestamp" type="datetime-local">
        <input id="id_name" name="name" type="text">
        <textarea id="id_description" name="description"></textarea>
    </form>
</script>

<script type="text/html" id="tmpl-category-form">
    <form id="add-category">
        <input id="id_name" name="name" type="text">
    </form>
</script>

<script>

var app = window.app = {
    url: {
        add: {
            category: "{% url 'add-category' %}",
            note: "{% url 'add-note' %}",
            place: "{% url 'add-place' %}",
            spending: "{% url 'add-spending' %}"
        },
        list: {
            category: "{% url 'list-category' %}",
            note: "{% url 'list-note' %}",
            place: "{% url 'list-place' %}",
            spending: "{% url 'list-spending' %}"
        }
    },
    templates: {
        add_spending_form: $('#tmpl-add-spending-form').html(),
        add_place_form: $('#tmpl-add-place-form').html(),
        add_note_form: $('#tmpl-note-form').html(),
        add_category_form: $('#tmpl-category-form').html(),
    },
    pages: {
        $spending: $('log-spending-page'),
        $place: $('log-place-page'),
        $note: $('log-note-page'),
        $category: $('log-category-page')
    },
    map: {
        selector: ['#map'],
        map: undefined,
        markers: []
    },
    loaded: {
        doc: false,
        map: false
    }
}

$('.add-links li').on('click', 'a', function(e) {
    e.preventDefault();
    let page_name = $(this).attr('href').split('-')[1];
    let tmpl = app.templates['add_'+page_name+'_form'];
    let page = app.pages['$'+page_name];

    debugger;
    console.log(tmpl);
    page.html(tmpl);
    console.log(page);
});

function initMap(position) {
    app.map.map = new google.maps.Map(document.querySelector(app.map.selector[0]), {
        zoom: 20,
        center: position
    });
    app.map.markers.push(new google.maps.Marker({
            position: position,
            map: map
        })
    );
}

function google_maps_ready(e) {
    app.loaded.map = true;
    $(document).trigger('loaded:map');
}

$(document).ready(function() {
    app.loaded.doc = true;
    $(document).trigger('loaded:doc');
});


$('#get-geo-location').on('click', function(e) {
    navigator.geolocation.getCurrentPosition(function(position) {
        var position = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
        };
    });
});

// $('#add-list').on('click', function(e) {
// 	e.preventDefaults();
// 	console.log("TODO add stuff");
// });

// $('#list-list').on('click', function(e) {
// 	e.preventDefaults();
// 	console.log("TODO click stuff");
// })
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBvVHQ8l3FnP9EpbZEktdh7uwGtw2dTziE&callback=google_maps_ready"></script>
{% endcomment %}

{% endblock %}

mt/places/templates/spending/jquery.html
<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
<script>window.jQuery || document.write('<script src="lib/jquery/jquery-2.1.4.js"><\/script>');</script>

mt/places/templates/spending/underscore.html
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
<script>
if(typeof(_) === 'undefined') {
    document.write('<script src="lib/underscore/underscore.js"><\/script>');
}
</script>